---
- name: Install requirements
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 36000
    name: 
      - apt-transport-https
      - ca-certificates
      - gnupg2

- name: Add docker official gpg key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
    # force: true # does not work well on slow connection

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install docker packages
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 36000
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - enable docker
    - start docker

- name: Copy daemon.json config of docker service
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  notify:
    - daemon-reload
    - restart docker
    - delete /var/lib/docker
