version: '3'

networks:
  web:
    external: true
  app:

volumes:
  mariadb_data:
  wordpress_data:

services:
  mariadb:
    image: localhost/bitnami/mariadb:11.2
    container_name: mariadb
    restart: unless-stopped
    networks:
      - app
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=wordpress

  wordpress:
    image: localhost/bitnami/wordpress:6
    container_name: wordpress
    restart: unless-stopped
    networks:
      - web
      - app
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=user
      - WORDPRESS_DATABASE_NAME=wordpress
