version: '3'

networks:
  web:
    external: true
  app:

services:
  mariadb:
    image: localhost/library/mariadb:11.3
    container_name: mariadb
    networks:
      - app
    volumes:
      - /data/mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  wordpress:
    image: localhost/library/wordpress:6
    container_name: wordpress
    networks:
      - web
      - app
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
